### ISSUE TITLE
Missing scripts ftinfo.py and ettrustinfo.py

### ISSUE THREAD

**Issue by vruello** [dirkjanm/forest-trust-tools#1]
Hi,

In your "Walking your dog in multiple forests" presentation at BH Asia 2020, you mentioned 2 scripts (ftinfo.py and ettrustinfo.py) of this repository which are not there.

I was wondering if you are planning to publish them at sometime, or maybe you changed your mind?

Thank you,

**Comment by cnotin** [comment]
Same question here :)

**Comment by dirkjanm** [comment]
they have been added, sorry for the delay!
